source 'https://github.com/CocoaPods/Specs.git'

target 'ArtikCloudClient' do
  pod "ArtikCloud", :path => "../"
end

target 'ArtikCloudClientTests' do
  pod "ArtikCloud", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
